### ISSUE TITLE
homologs broken upon click: no way to get the destination genes

### ISSUE THREAD

**Issue by iosonofabio** [fabilab/cell_atlas_approximations_HI#108]
```
show homologs of AT5G03170, AT1G20850, AT2G40320, AT5G16490 from arabidopsis to rice
```

(click on any area)

![2024-08-07_18-55](https://github.com/user-attachments/assets/56d984d4-212f-4445-8e53-7f228f8fd105)

**Comment by iosonofabio** [comment]
clearly still broken...

**Comment by YingX97** [comment]
Hey Fabio, 
I pulled the latest code from this repo and merged it with mine. Based on your screenshot, so far, everything is working fine, including the feature where you can click on the gene name and it auto-create a query in the chatbox. This works on different browsers (chrome, safari, MS Edge). 

I am just wondering if the code you deployed is the same in this repo, and also wondering what browser are you using? I am trying to reproduce the error. 

Cheers
<img width="1204" alt="Screen Shot 2024-08-07 at 9 25 14 pm" src="https://github.com/user-attachments/assets/521a2eff-d17e-4236-9342-5fb376ee3f50">

**Comment by iosonofabio** [comment]
how do I select a bunch of rice genes to get the sequences?

**Comment by YingX97** [comment]
I haven't come up with a good way to do this as in some cases there are over 100 homologs from the returned data. The current solution is that users can download the plot data as csv and then they can copy the genes from that file.

<img width="873" alt="Screen Shot 2024-08-07 at 9 41 36 pm" src="https://github.com/user-attachments/assets/824a579a-9f7f-457b-8e1b-44d5ab3bb539">

**Comment by YingX97** [comment]
hmm, I have been trying to make these gene labels selectable by the user via their cursor. But plotly haven't allowed this action yet, it is still an open ticket on their repo. https://github.com/plotly/plotly.js/issues/5320

**Comment by iosonofabio** [comment]
> I haven't come up with a good way to do this as in some cases there are over 100 homologs from the returned data. The current solution is that users can download the plot data as csv and then they can copy the genes from that file.
> <img alt="Screen Shot 2024-08-07 at 9 41 36 pm" width="873" src="https://private-user-images.githubusercontent.com/98261770/355798809-824a579a-9f7f-457b-8e1b-44d5ab3bb539.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzE2ODgsIm5iZiI6MTcyMzAzMTM4OCwicGF0aCI6Ii85ODI2MTc3MC8zNTU3OTg4MDktODI0YTU3OWEtOWY3Zi00NTdiLThlMWItNDRkNWFiM2JiNTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDExNDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NGU1NzZhZmEwNTQwODIxYzlkMGNhYzdjYjU0MDJmNGJmYWVlNWRlZWVlZTc2MmJkNDU0ZWQzMTI4MTljNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xJveCjBGDn7DVupPCrOyueP9AVXjv1Vfmi-hTgi-QNo">

sure but the fact remains that next week I am giving a demo with 10 genes total and I have to retype 15-letter rice gene ids because you are afraid of a corner case.

Why don't you add some text in the chat box about the first 20 homolog genes and then put some ellipses...

**Comment by YingX97** [comment]
Yep I will change the suggested pop up query.

**Comment by YingX97** [comment]
Fixed in https://github.com/fabilab/cell_atlas_approximations_HI/pull/109
