### ISSUE TITLE
 what is the expression of Cox4i2 in mouse pericyte across organs?

### ISSUE THREAD

**Issue by iosonofabio** [fabilab/cell_atlas_approximations_HI#118]
gives empty chat window

@YingX97

**Comment by YingX97** [comment]
Fixed via PR : https://github.com/fabilab/cell_atlas_approximations_HI/pull/119

**Comment by iosonofabio** [comment]
This is more general. In no case should the chatbot return empty answer. Are you sure that's the case now? 

Great idea with the PR
