### ISSUE TITLE
most landing page questions are broken

### ISSUE THREAD

**Issue by iosonofabio** [fabilab/cell_atlas_approximations_HI#18]
@YingX97 

just tried a bunch of the landing page questions and they are all broken with some error in updateChat that is not informative... could you take a look on Monday please?

Thank you!

**Comment by YingX97** [comment]
Hey Fabio, 

The bug is fixed.

**Comment by iosonofabio** [comment]
I'm not sure what happened, but this appeared to reveal a really, really strange discrepancy between node and frontend JS. We can have a chat next week, for now I used a hack in the entity extraction to get this to work.

Not sure if you found another way to fix it independently.
