### ISSUE TITLE
organism profile for chromatin accessibility

### ISSUE THREAD

**Issue by iosonofabio** [fabilab/cell_atlas_approximations_HI#25]
Human data is already there, more on the way. It would be good to have this feature implemented at some point.

**Comment by YingX97** [comment]
I think we need a new intent to implement this feature,
e.g: explore.organism.chromatinAccessibility

**Comment by iosonofabio** [comment]
Ok, can you open an issue in the nlp repo?

**Comment by YingX97** [comment]
Implemented in https://github.com/fabilab/cell_atlas_approximations_HI/pull/48
