### ISSUE TITLE
zoom in, then log fails

### ISSUE THREAD

**Issue by iosonofabio** [fabilab/cell_atlas_approximations_HI#30]
getting marker genes for rod cells in frog eye, then zoom in, then log -> blank page

I remember you have fairly spaghetti code for these things, so there's probably a bug there somewhere ;-)

**Comment by YingX97** [comment]
Fixed in https://github.com/fabilab/cell_atlas_approximations_HI/pull/35

**Comment by YingX97** [comment]
fixed and merged.
