### ISSUE TITLE
 show expression of HBA1, KDM7A-DT, HBA2, MARK3, KAT2B, YOD1, FBXO9, KIAA0232, TTPAL, SLC25A37, HBB in human marrow

### ISSUE THREAD

**Issue by iosonofabio** [fabilab/cell_atlas_approximations_HI#31]
check if this works

**Comment by YingX97** [comment]
Hi Fabio,

The nlp truncates the genes when there is a hyphen(-) in the gene name. This is the params:
{
    "features": "HBA1,KDM7A",
    "organism": "h_sapiens",
    "organ": "marrow"
}.

**Comment by YingX97** [comment]
Fixed in nlp: https://github.com/fabilab/cell_atlas_approximations_NLP/issues/26
