### ISSUE TITLE
co-expression scatter plot for 2 genes

### ISSUE THREAD

**Issue by iosonofabio** [fabilab/cell_atlas_approximations_HI#70]
I received a request for a scatter plot for a pair of genes, across a whole organism.

I'll implement the API and NLP, would be great if you could implement the frontend @YingX97 

Thank you!

**Comment by iosonofabio** [comment]
I just pushed `@fabilab/atlasapprox-nlp` 0.2.32 to NPM, there's a new intent: `comeasurement.geneExpression` with slots for organism and features.

**Comment by YingX97** [comment]
https://github.com/fabilab/cell_atlas_approximations_HI/pull/71
